In [27]:
import torch
def activation(x):
    return 1/(1+torch.exp(x))
torch.manual_seed(7)
features=torch.randn((1,5))
weights=torch.randn_like(features)
bias=torch.randn((1,1))
# y=activation(torch.sum(features*weights)+bias)
y=activation((features*weights).sum()+bias)

In [28]:
print (y)

tensor([[0.8405]])


In [29]:
weights.view(5,1)

tensor([[-0.8948],
        [-0.3556],
        [ 1.2324],
        [ 0.1382],
        [-1.6822]])

In [30]:
weights.view(1,5)

tensor([[-0.8948, -0.3556,  1.2324,  0.1382, -1.6822]])

In [31]:
weights.view(5,1)

tensor([[-0.8948],
        [-0.3556],
        [ 1.2324],
        [ 0.1382],
        [-1.6822]])

In [33]:
y=activation(torch.mm(features,weights.view(5,1))+1)

In [35]:
print(y)

tensor([[0.7270]])


In [36]:
###MULTILAYER NETWORKS

In [37]:
torch.manual_seed(7)
features = torch.randn((1, 3))
n_input = features.shape[1] 
n_hidden = 2  
n_output = 1
W1 = torch.randn(n_input, n_hidden)
W2 = torch.randn(n_hidden, n_output)
B1 = torch.randn((1, n_hidden))
B2 = torch.randn((1, n_output))

In [38]:
h = activation(torch.mm(features, W1) + B1)
output = activation(torch.mm(h, W2) + B2)
print(output)

tensor([[0.5290]])


In [39]:
#NUMPY TO TORCH AND BACK.

In [40]:
import numpy as np
a=np.random.rand(4,3)


In [41]:
a

array([[0.26472413, 0.11279025, 0.63339219],
       [0.7116332 , 0.40279801, 0.48293331],
       [0.53188964, 0.31124536, 0.07237347],
       [0.61664893, 0.58630051, 0.03157724]])

In [42]:
b=torch.from_numpy(a)

In [43]:
b

tensor([[0.2647, 0.1128, 0.6334],
        [0.7116, 0.4028, 0.4829],
        [0.5319, 0.3112, 0.0724],
        [0.6166, 0.5863, 0.0316]], dtype=torch.float64)

In [44]:
b.numpy()

array([[0.26472413, 0.11279025, 0.63339219],
       [0.7116332 , 0.40279801, 0.48293331],
       [0.53188964, 0.31124536, 0.07237347],
       [0.61664893, 0.58630051, 0.03157724]])

In [45]:
b.mul_(2)

tensor([[0.5294, 0.2256, 1.2668],
        [1.4233, 0.8056, 0.9659],
        [1.0638, 0.6225, 0.1447],
        [1.2333, 1.1726, 0.0632]], dtype=torch.float64)

In [46]:
a

array([[0.52944825, 0.22558051, 1.26678437],
       [1.42326639, 0.80559602, 0.96586661],
       [1.06377929, 0.62249071, 0.14474694],
       [1.23329786, 1.17260101, 0.06315449]])

In [48]:
%matplotlib inline
%config InlineBackend.figure_format='retina'

import numpy as np
import torch
import helper
import matplotlib.pyplot as plt

ModuleNotFoundError: No module named 'matplotlib'

In [49]:
%matplotlib inline
%config InlineBackend.figure_format = 'retina'

import numpy as np
import torch

import helper

import matplotlib.pyplot as plt

ModuleNotFoundError: No module named 'matplotlib'

In [51]:

import numpy as np
import torch

import helper

import matplotlib.pyplot as plt

In [55]:
from torchvision import datasets,transforms
transform=transforms.Compose([transforms.ToTensor(),transforms.Normalize((0.5,),(0.5)),])

trainset = datasets.MNIST('~/.pytorch/MNIST_data/', download=True, train=True, transform=transform)
trainloader = torch.utils.data.DataLoader(trainset, batch_size=64, shuffle=True)

Processing...
Done!


In [58]:
for image, label in trainloader:
    dataiter = iter(trainloader)
    images, labels = dataiter.next()
    print(type(images))
    print(images.shape)
    print(labels.shape)
    

TypeError: zip argument #3 must support iteration